In [7]:
from utils import create_mask
import torch
mask=create_mask(height=3,width=3,probability=0.5, mode='bernoulli')
print(mask)
x=torch.randn((3,3,3))
print(x)
print(x*mask)
print(x*(1-mask))

tensor([[[0., 1., 1.],
         [0., 0., 0.],
         [0., 1., 0.]],

        [[0., 1., 1.],
         [0., 0., 0.],
         [0., 1., 0.]],

        [[0., 1., 1.],
         [0., 0., 0.],
         [0., 1., 0.]]])
tensor([[[ 1.5587e+00,  1.2869e+00, -1.5428e+00],
         [ 2.3105e-01,  6.9634e-01, -2.0371e-01],
         [-7.7999e-01, -1.1145e+00, -7.5164e-01]],

        [[-7.5085e-02, -8.9132e-01, -2.3339e-01],
         [ 9.3364e-01, -1.2444e+00, -3.5584e-01],
         [-4.9491e-01, -1.6210e+00, -6.2670e-01]],

        [[-4.6280e-01,  5.7055e-04,  1.0970e+00],
         [ 2.7114e-01, -2.8852e-02, -1.3573e+00],
         [-1.4513e+00, -4.9570e-01, -9.8553e-01]]])
tensor([[[ 0.0000e+00,  1.2869e+00, -1.5428e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00],
         [-0.0000e+00, -1.1145e+00, -0.0000e+00]],

        [[-0.0000e+00, -8.9132e-01, -2.3339e-01],
         [ 0.0000e+00, -0.0000e+00, -0.0000e+00],
         [-0.0000e+00, -1.6210e+00, -0.0000e+00]],

        [[-0.0000e+00,  5.7