In [1]:
from utils import create_mask
import torch
mask=create_mask(height=3,width=3,probability=0.5, mode='bernoulli')
print(mask)
x=torch.randn((3,3,3))
print(x)
print(x*mask)
print(x*(1-mask))

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [1., 1., 1.]])
tensor([[[-0.4380,  0.2771,  1.3311],
         [ 0.2776,  0.2394,  0.1821],
         [-0.5370, -0.4340, -1.6707]],

        [[-0.0457,  0.2544,  2.4002],
         [-0.4542, -0.9640,  0.5224],
         [ 0.9537, -1.7963,  0.1459]],

        [[ 0.5814,  0.1576, -0.1730],
         [-0.9892,  1.5974, -2.1565],
         [ 0.4812,  0.6286, -0.9715]]])
tensor([[[-0.4380,  0.2771,  1.3311],
         [ 0.0000,  0.2394,  0.1821],
         [-0.5370, -0.4340, -1.6707]],

        [[-0.0457,  0.2544,  2.4002],
         [-0.0000, -0.9640,  0.5224],
         [ 0.9537, -1.7963,  0.1459]],

        [[ 0.5814,  0.1576, -0.1730],
         [-0.0000,  1.5974, -2.1565],
         [ 0.4812,  0.6286, -0.9715]]])
tensor([[[-0.0000,  0.0000,  0.0000],
         [ 0.2776,  0.0000,  0.0000],
         [-0.0000, -0.0000, -0.0000]],

        [[-0.0000,  0.0000,  0.0000],
         [-0.4542, -0.0000,  0.0000],
         [ 0.0000, -0.0000,  0.0000]],

     